- hosts: all
  vars:
          - sw_name: "docker-ce-18.09.1-3.el7.x86_64"
  tasks:
          - name: Docker Repository
            yum_repository:
                   name: docker
                   description: Docker YUM repo
                   baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
                   gpgcheck: no
            register: yum_repo

          - name: Docker Insatllation
            package:
                    name: "{{ sw_name }}"
                    state: present
            when: yum_repo.failed == false
            register: installation


          - name: Docker Service
            service:
                    name: "docker"
                    state: started
            register: svc_status
            when: installation.failed == false

          - name: Docker SDK for python3 
            command: pip3 install docker 

          - name: Create a data container
            docker_container:
                   name: WebServer_Container
                   image: ashwani2399/webserver:v1
                   exposed_ports:
                           - "81"
                   ports:
                           - "81:80" 
                   volumes:
                           - /ansible_playcode/task1_playcode/webcode:/var/www/html
            register: container
            

          - debug:
                  msg: yum_repo.stdout
                  msg: installation.stdout
                  msg: container.stdout

   
                  

